<Project>

  <PropertyGroup>
    <Version>0.1.0-beta</Version>
    <Authors>Amtsblick-Mitwirkende</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/haraldrohan/Amtsblick</RepositoryUrl>
    <LangVersion>latest</LangVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

</Project>
