<Project>

  <PropertyGroup>
    <Version>0.1.3-beta</Version>
    <Authors>Amtsblick-Mitwirkende</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/haraldrohan/Amtsblick</RepositoryUrl>
    <LangVersion>latest</LangVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <!-- Nur das Server-Projekt wird als Paket ausgeliefert. -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
